version: '3'
services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mysql
    environment:
      NODE_ENV: development
      ENVIRONMENT: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: auth
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: root
    links:
      - mysql
      - redis
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - redis:/var/lib/redis
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql_data:
    driver: local
  redis:
    driver: local
