services:
  law-mysql:
    image: mysql:latest
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: 123456789
        MYSQL_DATABASE: law
        MYSQL_PASSWORD: 123456789
    networks:
        - app-network
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - law-mysql
    networks:
      - app-network
    environment:
      PMA_HOST: law-mysql
      UPLOAD_LIMIT: 300M
  law-service:
    build: ./law-service
    depends_on:
      - law-mysql
    ports:
      - 8080:8080
    volumes:
      - ./law-service:/app
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://law-mysql:3306/law?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
networks:
    app-network:
        driver: bridge