services:
    kong:
        image: kong:latest
        container_name: kong
        restart: always
        ports:
            - '8000:8000'
            - '8001:8001'
            - '8002:8002'
            - '8003:8003'
            - '8004:8004'
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
            KONG_PG_DATABASE: kong
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
        depends_on:
            - kong-database
    kong-database:
        image: postgres:9.6
        container_name: kong-database
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        volumes:
            - ./data:/var/lib/postgresql/data
