version: '3'
services:
    auth-service:
        image: node:latest
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run dev"
        ports:
            - '8000:8000'
        depends_on:
            - redis
            - auth-mysql
        environment:
            ENVIRONMENT: development
            DB_HOST: auth-mysql
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: auth
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: root
            ACCESS_TOKEN_KEY: VN-Law-Advisor
            REFRESH_TOKEN_KEY: auth-service
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - redis:/var/lib/redis
    auth-mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: auth
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - '8082:8080'
volumes:
    mysql_data:
    redis:
