name: build-docker

on:
  push:
    branches:
        - 'main'
  pull_request:
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:backend/auth-service"
          push: true
          tags: tghuy2002/vnlaw-auth:latest
      - name: Build and push law-service
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:backend/law-service"
          push: true
          tags: tghuy2002/vnlaw-law:latest
