name: Build docker for dockerhub

on:
  push:
    branches:
        - 'main'
    paths: ['backend/law-service/**', 'backend/auth-service/**', 'backend/rag/**']
  pull_request:
    branches: ['main']
    paths: ['backend/law-service/**', 'backend/auth-service/**', 'backend/rag/**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            auth-service:
              - 'backend/auth-service/**'
            law-service:
              - 'backend/law-service/**'
            qna-service:
              - 'backend/rag/**'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push auth-service
        if: steps.filter.outputs.auth-service == 'true'
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:backend/auth-service"
          push: true
          tags: tghuy2002/vnlaw-auth:latest
          filters: 
      - name: Build and push law-service
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.law-service == 'true'
        with:
          context: "{{defaultContext}}:backend/law-service"
          push: true
          tags: tghuy2002/vnlaw-law:latest
      - name: Build and push qna-service
        uses: docker/build-push-action@v5
        if: steps.filter.outputs.qna-service == 'true'
        with:
          context: "{{defaultContext}}:backend/rag"
          push: true
          tags: tghuy2002/vnlaw-qna:latest
