# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['auth-service']
        paths:
            - './backend/system/auth-service/**'
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./backend/system/auth-service
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
